import {Timestamp} from '@react-native-firebase/firestore';
import {
  questionMode,
  questionGrade,
  questionSettingState,
  questionState,
  taskAuthor,
  taskCalendarColor,
} from '../../types/commonUnionType';
import type {SettingCardDataMap} from '../hooks/useGlobalSaveDataContext';

export const dummySaveAndTaskData: SettingCardDataMap = {
  'saved-practice-0': {
    id: 'saved-practice-0',
    title: '保存した設定・練習0',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.saved,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: [
        'big-学科Ⅰ-計画原論',
        'small-学科Ⅰ-計画原論-光',
        'small-学科Ⅰ-計画原論-気候・空気',
        'small-学科Ⅰ-計画原論-熱',
        'small-学科Ⅰ-計画原論-環境工学全般',
        'small-学科Ⅰ-計画原論-用語・単位',
        'small-学科Ⅰ-計画原論-色彩',
        'small-学科Ⅰ-計画原論-音',
      ],
      qaaQuestionCategory: [],
      questionFormat: ['pqs_questionFormat_fiveChoices'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: ['pqs_questionDifficulties_one'],
      questionCoverage: ['pqs_questionCoverage_all'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_10'],
    },
    isQaa: false,
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
  },
  'saved-practice-1': {
    id: 'saved-practice-1',
    title: '保存した設定・練習1',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.saved,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: [
        'small-学科Ⅰ-計画原論-気候・空気',
        'small-学科Ⅰ-計画原論-熱',
        'small-学科Ⅰ-計画原論-環境工学全般',
        'small-学科Ⅰ-計画原論-用語・単位',
        'small-学科Ⅰ-計画原論-色彩',
        'small-学科Ⅰ-計画原論-音',
      ],
      qaaQuestionCategory: [],
      questionFormat: ['pqs_questionFormat_fiveChoices'],
      questionOrder: ['pqs_questionOrder_inOrder'],
      questionDifficulties: ['pqs_questionDifficulties_one'],
      questionCoverage: ['pqs_questionCoverage_all'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_5'],
    },
    isQaa: false,
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
  },
  'saved-exam-0': {
    id: 'saved-exam-0',
    title: '保存した設定・模擬試験0',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.saved,
    questionMode: questionMode.exam,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [],
      questionFormat: [],
      questionOrder: [],
      questionDifficulties: [],
      questionCoverage: [],
      option: [],
      numberOfQuestions: [],
      questionTime: [],
    },
    isQaa: false,
    examQuestionSetting: {
      subject: ['eqs_2級_subjectOneTwo'],
      numberOfQuestions: ['eqs_2級_subjectOneTwo_NumberOfQuestions_half'],
    },
  },
  'saved-exam-1': {
    id: 'saved-exam-1',
    title: '保存した設定・模擬試験1',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.saved,
    questionMode: questionMode.exam,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [],
      questionFormat: [],
      questionOrder: [],
      questionDifficulties: [],
      questionCoverage: [],
      option: [],
      numberOfQuestions: [],
      questionTime: [],
    },
    isQaa: false,
    examQuestionSetting: {
      subject: ['eqs_2級_subjectOneTwo'],
      numberOfQuestions: ['eqs_2級_subjectOneTwo_NumberOfQuestions_full'],
    },
  },
  'task-practice-20240901-0-d': {
    // ～昨日・未着手・あなた
    id: 'task-practice-20240901-0-d',
    title: '練習課題1',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: [
        'small-学科Ⅲ-その他の建築材料-建築材料融合',
        'big-学科Ⅲ-その他の建築材料',
      ],
      qaaQuestionCategory: [],
      questionFormat: ['pqs_questionFormat_fiveChoices'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: ['pqs_questionDifficulties_one'],
      questionCoverage: ['pqs_questionCoverage_all'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_10'],
    },
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
    isQaa: false,
    taskSetting: {
      isOpen: true,
      taskState: questionState.notStarted,
      isTeacher: false,
      author: taskAuthor.user,
      taskDate: [
        {
          startAt: Timestamp.fromDate(new Date('2024-09-01T00:00:00.000')),
          endAt: Timestamp.fromDate(new Date('2024-09-01T23:59:59.999')),
        },
      ],
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '練習課題1のメモ',
      taskCalendarColor: taskCalendarColor.violet,
      hasTask: true,
    },
  },
  'task-exam-20240905-1-d': {
    // 今日・途中・あなた
    id: 'task-exam-20240905-1-d',
    title: '模擬試験1',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.exam,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [],
      questionFormat: [],
      questionOrder: [],
      questionDifficulties: [],
      questionCoverage: [],
      option: [],
      numberOfQuestions: [],
      questionTime: [],
    },
    examQuestionSetting: {
      subject: ['eqs_2級_subjectOneTwo'],
      numberOfQuestions: ['eqs_2級_subjectOneTwo_NumberOfQuestions_half'],
    },
    isQaa: false,
    taskSetting: {
      isOpen: false,
      taskState: questionState.progress,
      isTeacher: false,
      author: taskAuthor.user,
      taskDate: [
        {
          startAt: Timestamp.fromDate(new Date('2024-09-05T00:00:00.000')),
          endAt: Timestamp.fromDate(new Date('2024-09-05T23:59:59.999')),
        },
      ],
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '模擬試験1のメモ',
      taskCalendarColor: taskCalendarColor.green,
      hasTask: true,
    },
  },
  'task-practice-20240905-2-d': {
    // 今日・未完了・あなた
    id: 'task-practice-20240905-2-d',
    title: '練習課題2',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [
        'small-学科Ⅳ-その他-施工機械・器具',
        'small-学科Ⅳ-その他-積算・見積',
        'small-学科Ⅳ-その他-測量',
        'big-学科Ⅳ-その他',
      ],
      questionFormat: ['pqs_questionFormat_qAndA'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: ['pqs_questionDifficulties_one'],
      questionCoverage: ['pqs_questionCoverage_all'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_10'],
    },
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
    isQaa: true,
    taskSetting: {
      isOpen: true,
      taskState: questionState.progress,
      isTeacher: false,
      author: taskAuthor.user,
      taskDate: [
        {
          startAt: Timestamp.fromDate(new Date('2024-09-05T00:00:00.000')),
          endAt: Timestamp.fromDate(new Date('2024-09-05T23:59:59.999')),
        },
      ],
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '練習課題2のメモ',
      taskCalendarColor: taskCalendarColor.blue,
      hasTask: true,
    },
  },
  'task-exam-20240905-0-d': {
    // 今日・完了・あなた
    id: 'task-exam-20240905-0-d',
    title: '模擬試験2',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.exam,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [],
      questionFormat: [],
      questionOrder: [],
      questionDifficulties: [],
      questionCoverage: [],
      option: [],
      numberOfQuestions: [],
      questionTime: [],
    },
    examQuestionSetting: {
      subject: ['eqs_2級_subjectThreeFour'],
      numberOfQuestions: ['eqs_2級_subjectThreeFour_NumberOfQuestions_half'],
    },
    isQaa: false,
    taskSetting: {
      isOpen: true,
      taskState: questionState.completed,
      isTeacher: false,
      author: taskAuthor.user,
      taskDate: [
        {
          startAt: Timestamp.fromDate(new Date('2024-09-05T00:00:00.000')),
          endAt: Timestamp.fromDate(new Date('2024-09-05T23:59:59.999')),
        },
      ],
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '模擬試験2のメモ',
      taskCalendarColor: taskCalendarColor.red,
      hasTask: true,
    },
  },
  'task-practice-20241001-0-d': {
    // 明日以降・完了・あなた
    id: 'task-practice-20241001-0-d',
    title: '練習課題3',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [
        'small-学科Ⅲ-その他の建築材料-建築材料融合',
        'big-学科Ⅲ-その他の建築材料',
      ],
      questionFormat: ['pqs_questionFormat_qAndA'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: ['pqs_questionDifficulties_one'],
      questionCoverage: ['pqs_questionCoverage_all'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_10'],
    },
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
    isQaa: true,
    taskSetting: {
      isOpen: true,
      taskState: questionState.completed,
      isTeacher: false,
      author: taskAuthor.user,
      taskDate: [
        {
          startAt: Timestamp.fromDate(new Date('2024-10-01T00:00:00.000')),
          endAt: Timestamp.fromDate(new Date('2024-10-01T23:59:59.999')),
        },
      ],
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '練習課題3のメモ',
      taskCalendarColor: taskCalendarColor.yellow,
      hasTask: true,
    },
  },
  'task-exam-20240902-1-d': {
    // ～昨日・未着手・講師・提出可
    id: 'task-exam-20240902-1-d',
    title: '模擬試験3',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.exam,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [],
      questionFormat: [],
      questionOrder: [],
      questionDifficulties: [],
      questionCoverage: [],
      option: [],
      numberOfQuestions: [],
      questionTime: [],
    },
    examQuestionSetting: {
      subject: ['eqs_2級_subjectOneTwo'],
      numberOfQuestions: ['eqs_2級_subjectOneTwo_NumberOfQuestions_half'],
    },
    isQaa: false,
    taskSetting: {
      isOpen: true,
      taskState: questionState.notStarted,
      author: taskAuthor.teacher,
      isTeacher: true,
      deadlineDate: Timestamp.fromDate(new Date('2024-09-02T23:59:59.999')),
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '模擬試験3のメモ',
      taskCalendarColor: taskCalendarColor.orange,
      hasTask: true,
    },
  },
  'task-practice-20240901-2-d': {
    // ～昨日・途中・講師・提出不可
    id: 'task-practice-20240901-2-d',
    title: '練習課題4',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [
        'small-学科Ⅲ-その他の建築材料-建築材料融合',
        'big-学科Ⅲ-その他の建築材料',
      ],
      questionFormat: ['pqs_questionFormat_qAndA'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: ['pqs_questionDifficulties_one'],
      questionCoverage: ['pqs_questionCoverage_all'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_10'],
    },
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
    isQaa: true,
    taskSetting: {
      isOpen: false,
      taskState: questionState.progress,
      isTeacher: true,
      author: taskAuthor.teacher,
      deadlineDate: Timestamp.fromDate(new Date('2024-09-01T23:59:59.999')),
      isAbleToAnswerAfterDeadline: false,
      isExpired: true,

      taskNotification: false,
      taskMemo: '練習課題4のメモ',
      taskCalendarColor: taskCalendarColor.blueGreen,
      hasTask: true,
    },
  },
  'task-exam-20240920-3-d': {
    // 明日以降・未着手・講師・提出可
    id: 'task-exam-20240920-3-d',
    title: '模擬試験4',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.exam,
    practiceQuestionSetting: {
      questionCategory: [],
      qaaQuestionCategory: [],
      questionFormat: [],
      questionOrder: [],
      questionDifficulties: [],
      questionCoverage: [],
      option: [],
      numberOfQuestions: [],
      questionTime: [],
    },
    examQuestionSetting: {
      subject: ['eqs_2級_subjectOneTwo'],
      numberOfQuestions: ['eqs_2級_subjectOneTwo_NumberOfQuestions_half'],
    },
    isQaa: false,
    taskSetting: {
      isOpen: true,
      taskState: questionState.notStarted,
      isTeacher: true,
      author: taskAuthor.teacher,
      deadlineDate: Timestamp.fromDate(new Date('2024-09-20T23:59:59.999')),
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '模擬試験4のメモ',
      taskCalendarColor: taskCalendarColor.blueGreen,
      hasTask: true,
    },
  },
  'task-practice-20240920-2-d': {
    // 明日以降・途中・講師
    id: 'task-practice-20240920-2-d',
    title: '練習課題5',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: ['small-学科Ⅰ-計画原論-光'],
      qaaQuestionCategory: [],
      questionFormat: ['pqs_questionFormat_fiveChoices'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: [
        'pqs_questionDifficulties_two',
        'pqs_questionDifficulties_three',
      ],
      questionCoverage: ['pqs_questionCoverage_bothUnCorrectlyAndWeakSpot'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_5'],
    },
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
    isQaa: false,
    taskSetting: {
      isOpen: true,
      taskState: questionState.progress,
      isTeacher: true,
      author: taskAuthor.teacher,
      deadlineDate: Timestamp.fromDate(new Date('2024-09-20T23:59:59.999')),
      isAbleToAnswerAfterDeadline: false,
      isExpired: false,
      taskNotification: false,
      taskMemo: '練習課題5のメモ',
      taskCalendarColor: taskCalendarColor.blueGreen,
      hasTask: true,
    },
  },
  'task-practice-20240920-3-d': {
    // 明日以降・途中・講師
    id: 'task-practice-20240920-3-d',
    title: '練習課題6',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: ['small-学科Ⅲ-一般構造-構造計画'],
      qaaQuestionCategory: [],
      questionFormat: ['pqs_questionFormat_fiveChoices'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: [
        'pqs_questionDifficulties_two',
        'pqs_questionDifficulties_three',
      ],
      questionCoverage: ['pqs_questionCoverage_bothUnCorrectlyAndWeakSpot'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_30'],
    },
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
    isQaa: false,
    taskSetting: {
      isOpen: true,
      taskState: questionState.progress,
      isTeacher: true,
      author: taskAuthor.teacher,
      deadlineDate: Timestamp.fromDate(new Date('2024-09-20T23:59:59.999')),
      isAbleToAnswerAfterDeadline: false,
      isExpired: false,
      taskNotification: false,
      taskMemo: '練習課題6のメモ',
      taskCalendarColor: taskCalendarColor.blueGreen,
      hasTask: true,
    },
  },
  'task-practice-20240920-4-d': {
    // 明日以降・完了・講師
    id: 'task-practice-20240920-4-d',
    title: '練習課題7',
    grade: questionGrade.gradeTwo,
    settingState: questionSettingState.task,
    questionMode: questionMode.practice,
    practiceQuestionSetting: {
      questionCategory: ['small-学科Ⅲ-一般構造-構造計画'],
      qaaQuestionCategory: [],
      questionFormat: ['pqs_questionFormat_fiveChoices'],
      questionOrder: ['pqs_questionOrder_random'],
      questionDifficulties: [
        'pqs_questionDifficulties_two',
        'pqs_questionDifficulties_three',
      ],
      questionCoverage: ['pqs_questionCoverage_bothUnCorrectlyAndWeakSpot'],
      option: ['pqs_option_shuffleChoices'],
      numberOfQuestions: ['pqs_numberOfQuestions_5'],
      questionTime: ['pqs_questionTime_input_30'],
    },
    examQuestionSetting: {
      subject: [],
      numberOfQuestions: [],
    },
    isQaa: false,
    taskSetting: {
      isOpen: true,
      taskState: questionState.completed,
      isTeacher: true,
      author: taskAuthor.teacher,
      deadlineDate: Timestamp.fromDate(new Date('2024-09-20T23:59:59.999')),
      isAbleToAnswerAfterDeadline: true,
      isExpired: false,
      taskNotification: false,
      taskMemo: '練習課題7のメモ',
      taskCalendarColor: taskCalendarColor.blueGreen,
      hasTask: true,
    },
  },
};
